#
# Deployment for Proxima.Host
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxima-host-deployment
  labels:
    app: proxima-host
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxima-host
  template:
    metadata:
      labels:
        app: proxima-host
    spec:
      containers:
      - name: proxima-host
        image: proximadev.azurecr.io/proxima-host:latest
        ports:
          - containerPort: 8080
          - containerPort: 8081

---
#
# Service for Proxima.Host
#
apiVersion: v1
kind: Service
metadata:
  name: proxima-host-service
spec:
  selector:
    app: proxima-host
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
#
# Deployment for the Proxima UI
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxima-ui-deployment
  labels:
    app: proxima-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxima-ui
  template:
    metadata:
      labels:
        app: proxima-ui
    spec:
      containers:
      - name: proxima-ui
        image: proximadev.azurecr.io/proxima-ui:latest
        ports:
          - containerPort: 80

---
#
# Service for the Proxima UI
#
apiVersion: v1
kind: Service
metadata:
  name: proxima-ui-service
spec:
  selector:
    app: proxima-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
#
# Ingress Resource (routes /api to Proxima.Host, / to Proxima.UI)
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxima-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"  # OR "traefik" depending on your Ingress Controller
spec:
  rules:
    - http:
        paths:
          # All requests to /api get forwarded to Proxima.Host
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: proxima-host-service
                port:
                  number: 80
          # Everything else goes to the Proxima.UI
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxima-ui-service
                port:
                  number: 80
